project:
  type: book

book:
  title: Handbuch IT in Bibliotheken
  #author: ...
  date: today
  repo-url: https://github.com/pro4bib/handbuch-it-in-bibliotheken/
  repo-actions:
    - source
    - edit
    - issue
  chapters:
    - index.md  # = einleitung.md
    - management.md
    - anforderungen.md
    - bibliotheksmanagementsysteme.md
    - literatur.md
  appendices:
    - glossar.md
    - zielgruppe.md
    - styleguide.md
  sidebar:
    style: docked
    logo: media/VZG_Logo_Schriftzug.png
  # abstract: TODO
  # description: Description metadata for HTML version of book
  page-footer: 
    left: "[CC BY 3.0 DE](https://creativecommons.org/licenses/by/3.0/de/)"
    right: 
      - '<a class="nav-link" href="https://www.gbv.de/" alt="VZG">hosted by VZG</a>'
      - icon: github
        href: https://github.com/pro4bib/handbuch-it-in-bibliotheken/

bibliography: references.bib 

lang: de
number-sections: false
number-depth: 1

format:
  html:
    theme: cosmo
    css: style.css
    link-external-icon: true
    email-obfuscation: javascript
    header-includes: '<link rel="canonical" href="https://it-in-bibliotheken.de/?_KAPITEL_" />'
    include-before-body: templates/chapters.html
    include-after-body: templates/script.html
    callout-appearance: simple
  docx: {}
  #pdf:
  #  documentclass: scrreprt

#comments:
#  hypothesis: true
